// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: moneyconverter/money_converter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoneyConverter_Convert_FullMethodName = "/pb.MoneyConverter/Convert"
)

// MoneyConverterClient is the client API for MoneyConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoneyConverterClient interface {
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
}

type moneyConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewMoneyConverterClient(cc grpc.ClientConnInterface) MoneyConverterClient {
	return &moneyConverterClient{cc}
}

func (c *moneyConverterClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, MoneyConverter_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoneyConverterServer is the server API for MoneyConverter service.
// All implementations must embed UnimplementedMoneyConverterServer
// for forward compatibility.
type MoneyConverterServer interface {
	Convert(context.Context, *ConvertRequest) (*ConvertResponse, error)
	mustEmbedUnimplementedMoneyConverterServer()
}

// UnimplementedMoneyConverterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoneyConverterServer struct{}

func (UnimplementedMoneyConverterServer) Convert(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedMoneyConverterServer) mustEmbedUnimplementedMoneyConverterServer() {}
func (UnimplementedMoneyConverterServer) testEmbeddedByValue()                        {}

// UnsafeMoneyConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoneyConverterServer will
// result in compilation errors.
type UnsafeMoneyConverterServer interface {
	mustEmbedUnimplementedMoneyConverterServer()
}

func RegisterMoneyConverterServer(s grpc.ServiceRegistrar, srv MoneyConverterServer) {
	// If the following call pancis, it indicates UnimplementedMoneyConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoneyConverter_ServiceDesc, srv)
}

func _MoneyConverter_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyConverterServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyConverter_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyConverterServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoneyConverter_ServiceDesc is the grpc.ServiceDesc for MoneyConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoneyConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MoneyConverter",
	HandlerType: (*MoneyConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _MoneyConverter_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moneyconverter/money_converter.proto",
}
