api:
  url: "https://openexchangerates.org/api/latest.json"
  key: "da7046fc817e4b9794df828d24c80027"
aws:
  region: "us-west-2"
  accessKeyID: "dummy"
  secretAccessKey: "dummy"
server:
  endpoint: "http://localhost:8000"