version: '3'

services:
  currency-conversion-service:
    build: .
    container_name: currency-conversion-service
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
    volumes:
      - ./config.yaml:/root/config.yaml
    ports:
      - "50051:50051"  # gRPC port
      - "8085:8085"    # HTTP port
    networks:
      - kafka_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "localhost:127.0.0.1"
      - "host.docker.internal:host-gateway"
    dns_search: .

networks:
  kafka_network:
    external: true