// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: proto/money_converter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyConverter_Convert_FullMethodName = "/pb.CurrencyConverter/Convert"
)

// CurrencyConverterClient is the client API for CurrencyConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyConverterClient interface {
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
}

type currencyConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyConverterClient(cc grpc.ClientConnInterface) CurrencyConverterClient {
	return &currencyConverterClient{cc}
}

func (c *currencyConverterClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, CurrencyConverter_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyConverterServer is the server API for CurrencyConverter service.
// All implementations must embed UnimplementedCurrencyConverterServer
// for forward compatibility.
type CurrencyConverterServer interface {
	Convert(context.Context, *ConvertRequest) (*ConvertResponse, error)
	mustEmbedUnimplementedCurrencyConverterServer()
}

// UnimplementedCurrencyConverterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyConverterServer struct{}

func (UnimplementedCurrencyConverterServer) Convert(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedCurrencyConverterServer) mustEmbedUnimplementedCurrencyConverterServer() {}
func (UnimplementedCurrencyConverterServer) testEmbeddedByValue()                           {}

// UnsafeCurrencyConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyConverterServer will
// result in compilation errors.
type UnsafeCurrencyConverterServer interface {
	mustEmbedUnimplementedCurrencyConverterServer()
}

func RegisterCurrencyConverterServer(s grpc.ServiceRegistrar, srv CurrencyConverterServer) {
	// If the following call pancis, it indicates UnimplementedCurrencyConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyConverter_ServiceDesc, srv)
}

func _CurrencyConverter_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyConverterServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyConverter_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyConverterServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyConverter_ServiceDesc is the grpc.ServiceDesc for CurrencyConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CurrencyConverter",
	HandlerType: (*CurrencyConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _CurrencyConverter_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/money_converter.proto",
}
